# fly.toml app configuration file generated for aisha-eye-tracking-backend on 2025-10-20T22:50:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aisha-eye-tracking-backend"
primary_region = "sjc"

[build]

[env]
  PORT = "8765"

[http_service]
  internal_port = 8765
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[services]]
  protocol = "tcp"
  internal_port = 8765

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
