# Netlify Configuration for A.Isha Lipsync Avatar

[build]
  # Base directory where the build should run
  base = "wawa-lipsync/examples/lipsync-demo"
  
  # Build command
  command = "npm run build"
  
  # Directory with the final build output
  publish = "wawa-lipsync/examples/lipsync-demo/dist"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"


